language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: divshot
  skip_cleanup: true
  on:
    all_branches: true
  api_key:
    secure: na2HF37J5vt8RVlG921S5GxYCVK49VytJagNXH+cHEhuv1/xTNaSbz2jKNiq9aFUByWGPo0L7gvX7q1c0BekuFpBK5DZgesrqwXtra189FQiARXfKtk2qeXjkoG7bvO2lb77+iMUhgVc9ozJLutdt2zwlir3McC4LuN22/4gtO0=
notifications:
  slack:
    secure: SsIJ12xo88IQ075H7R9fLMSclOWKoC4vMAT7b9HOffRNsaEd6sEHZnKaSb5MGvs3cyBLKsTWOvEXNWZwmGxq8cstmhhgIbUE4S0RGHWff/9zwI97fSccZEqlo+T8Zi5t14dJezfcczL50PnoFBJH9tQmp5ipch54UWra3rDn14A=
