language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: divshot
  skip_cleanup: true
  on: production
  api_key:
    secure: mLuvEXM3vBTsh5QUg/KizvgwqxHGdOhrxtRfZ0tLLJJKNBhXDIB2XybrNjC2No4vLCN+wncNsAvMEuHQuqpPYkjgw7DazK73YgJDHk6bRQtTZ81PjeJ14FIx9haX+LbVng5/DnelnsnSSchJ52Os5/Hc7M/pa4+HxRBsnZj7Y5o=
  on:
    all_branches: true