language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: divshot
  skip_cleanup: true
  on:
    all_branches: true
  api_key:
    secure: na2HF37J5vt8RVlG921S5GxYCVK49VytJagNXH+cHEhuv1/xTNaSbz2jKNiq9aFUByWGPo0L7gvX7q1c0BekuFpBK5DZgesrqwXtra189FQiARXfKtk2qeXjkoG7bvO2lb77+iMUhgVc9ozJLutdt2zwlir3McC4LuN22/4gtO0=
